FROM mcr.microsoft.com/devcontainers/python:3.11

# Optional: system packages you might need
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive         && apt-get -y install --no-install-recommends build-essential curl git

WORKDIR /workspaces/f1-ml-codespaces
